
biagri_offre:
    resource: "@BiagriBundle/Resources/config/routing/offre.yml"
    prefix:   /offre

biagri_offre:
    resource: "@BiagriBundle/Resources/config/routing/offre.yml"
    prefix:   /offre


biagri_homepage:
    path:     /
    defaults: { _controller: BiagriBundle:Default:index }
