
biagri_offre:
    resource: "@BiagriBundle/Resources/config/routing/offre.yml"
    prefix:   /offre


biagri_vendeur:
    resource: "@BiagriBundle/Resources/config/routing/vendeur.yml"
    prefix:   /vendeur

biagri_tarifs:
    resource: "@BiagriBundle/Resources/config/routing/tarifs.yml"
    prefix:   /tarifs

biagri_homepage:
    path:     /
    defaults: { _controller: BiagriBundle:Default:index }
