acheteur_show:
    path:     /{id}/show
    defaults: { _controller: "BiagriBundle:Acheteur:show" }
    methods:  GET

acheteur_new:
    path:     /
    defaults: { _controller: "BiagriBundle:Acheteur:new" }
    methods:  [GET, POST]

acheteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiagriBundle:Acheteur:edit" }
    methods:  [GET, POST]

acheteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiagriBundle:Acheteur:delete" }
    methods:  DELETE
