BiagriBundle\Entity\Offre:
    type: entity
    table: null
    repositoryClass: BiagriBundle\Repository\OffreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        produits:
            type: string
            length: 255
        proteines:
            type: string
            length: 255
        ps:
            type: integer
        humidite:
            type: integer
        hagberg:
            type: integer
        livraison:
            type: string
            length: 255
        prixOffre:
            type: integer
            column: prix_offre
        societe:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        cp:
            type: string
            length: 255
        ville:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        mail:
            type: string
            length: 255
    lifecycleCallbacks: {  }
